--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST_USER
--------------------------------------------------------

  CREATE TABLE "HYY"."TEST_USER" 
   (	"SEQ" NUMBER(10,0), 
	"ID" VARCHAR2(100 BYTE), 
	"PWD" VARCHAR2(500 BYTE), 
	"CLNUM" VARCHAR2(500 BYTE),
	"REG_DATE" DATE, 
	"DEL_FLAG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HYY.TEST_USER
SET DEFINE OFF;
Insert into HYY.TEST_USER (SEQ,ID,PWD,REG_DATE,DEL_FLAG,CLNUM) values (1,'hyy','81DC9BDB52D04DC20036DBD8313ED055',to_date('25/07/10','RR/MM/DD'),'N',null);
Insert into HYY.TEST_USER (SEQ,ID,PWD,REG_DATE,DEL_FLAG,CLNUM) values (2,'hyy1','81DC9BDB52D04DC20036DBD8313ED055',to_date('25/07/10','RR/MM/DD'),'N',null);
--------------------------------------------------------
--  DDL for Index TEST_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYY"."TEST_USER_PK" ON "HYY"."TEST_USER" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TEST_USER
--------------------------------------------------------

  ALTER TABLE "HYY"."TEST_USER" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "HYY"."TEST_USER" ADD CONSTRAINT "TEST_USER_PK" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
