--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "HYY"."BOARD" 
   (	"NUM" NUMBER(6,0), 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENT" CLOB, 
	"WRITER" VARCHAR2(60 BYTE), 
	"WDATE" DATE DEFAULT SYSDATE, 
	"HIT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into HYY.BOARD
SET DEFINE OFF;
Insert into HYY.BOARD (NUM,TITLE,WRITER,WDATE,HIT) values (1,'title_1','writer01',to_date('25/07/16','RR/MM/DD'),0);
Insert into HYY.BOARD (NUM,TITLE,WRITER,WDATE,HIT) values (2,'title_2로변경한다.','writer02',to_date('25/07/16','RR/MM/DD'),0);
Insert into HYY.BOARD (NUM,TITLE,WRITER,WDATE,HIT) values (3,'title_3','writer03',to_date('25/07/16','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C008378
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYY"."SYS_C008378" ON "HYY"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "HYY"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HYY"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
